<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Account_statu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Account_statu_model');
    } 

    /*
     * Listing of account_status
     */
    function index()
    {
        $data['account_status'] = $this->Account_statu_model->get_all_account_status();
        
        $data['_view'] = 'account_statu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new account_statu
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
            );
            
            $account_statu_id = $this->Account_statu_model->add_account_statu($params);
            redirect('account_statu/index');
        }
        else
        {            
            $data['_view'] = 'account_statu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a account_statu
     */
    function edit($id)
    {   
        // check if the account_statu exists before trying to edit it
        $data['account_statu'] = $this->Account_statu_model->get_account_statu($id);
        
        if(isset($data['account_statu']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
                );

                $this->Account_statu_model->update_account_statu($id,$params);            
                redirect('account_statu/index');
            }
            else
            {
                $data['_view'] = 'account_statu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The account_statu you are trying to edit does not exist.');
    } 

    /*
     * Deleting account_statu
     */
    function remove($id)
    {
        $account_statu = $this->Account_statu_model->get_account_statu($id);

        // check if the account_statu exists before trying to delete it
        if(isset($account_statu['id']))
        {
            $this->Account_statu_model->delete_account_statu($id);
            redirect('account_statu/index');
        }
        else
            show_error('The account_statu you are trying to delete does not exist.');
    }
    
}
