<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Driver extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Driver_model');
    } 

    /*
     * Listing of driver
     */
    function index()
    {
        $data['driver'] = $this->Driver_model->get_all_driver();
        
        $data['_view'] = 'driver/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new driver
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('password','Password','required|max_length[100]');
		$this->form_validation->set_rules('name','Name','required|max_length[50]');
		$this->form_validation->set_rules('mobile','Mobile','required|integer');
		$this->form_validation->set_rules('email','Email','max_length[50]|valid_email');
		$this->form_validation->set_rules('address','Address','required|max_length[100]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'password' => $this->input->post('password'),
				'name' => $this->input->post('name'),
				'mobile' => $this->input->post('mobile'),
				'email' => $this->input->post('email'),
				'address' => $this->input->post('address'),
            );
            
            $driver_id = $this->Driver_model->add_driver($params);
            redirect('driver/index');
        }
        else
        {            
            $data['_view'] = 'driver/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a driver
     */
    function edit($id)
    {   
        // check if the driver exists before trying to edit it
        $data['driver'] = $this->Driver_model->get_driver($id);
        
        if(isset($data['driver']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('password','Password','required|max_length[100]');
			$this->form_validation->set_rules('name','Name','required|max_length[50]');
			$this->form_validation->set_rules('mobile','Mobile','required|integer');
			$this->form_validation->set_rules('email','Email','max_length[50]|valid_email');
			$this->form_validation->set_rules('address','Address','required|max_length[100]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'password' => $this->input->post('password'),
					'name' => $this->input->post('name'),
					'mobile' => $this->input->post('mobile'),
					'email' => $this->input->post('email'),
					'address' => $this->input->post('address'),
                );

                $this->Driver_model->update_driver($id,$params);            
                redirect('driver/index');
            }
            else
            {
                $data['_view'] = 'driver/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The driver you are trying to edit does not exist.');
    } 

    /*
     * Deleting driver
     */
    function remove($id)
    {
        $driver = $this->Driver_model->get_driver($id);

        // check if the driver exists before trying to delete it
        if(isset($driver['id']))
        {
            $this->Driver_model->delete_driver($id);
            redirect('driver/index');
        }
        else
            show_error('The driver you are trying to delete does not exist.');
    }
    
}
