<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Employee_type extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Employee_type_model');
    } 

    /*
     * Listing of employee_type
     */
    function index()
    {
        $data['employee_type'] = $this->Employee_type_model->get_all_employee_type();
        
        $data['_view'] = 'employee_type/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new employee_type
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required|max_length[50]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'name' => $this->input->post('name'),
            );
            
            $employee_type_id = $this->Employee_type_model->add_employee_type($params);
            redirect('employee_type/index');
        }
        else
        {            
            $data['_view'] = 'employee_type/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a employee_type
     */
    function edit($id)
    {   
        // check if the employee_type exists before trying to edit it
        $data['employee_type'] = $this->Employee_type_model->get_employee_type($id);
        
        if(isset($data['employee_type']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','required|max_length[50]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'name' => $this->input->post('name'),
                );

                $this->Employee_type_model->update_employee_type($id,$params);            
                redirect('employee_type/index');
            }
            else
            {
                $data['_view'] = 'employee_type/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The employee_type you are trying to edit does not exist.');
    } 

    /*
     * Deleting employee_type
     */
    function remove($id)
    {
        $employee_type = $this->Employee_type_model->get_employee_type($id);

        // check if the employee_type exists before trying to delete it
        if(isset($employee_type['id']))
        {
            $this->Employee_type_model->delete_employee_type($id);
            redirect('employee_type/index');
        }
        else
            show_error('The employee_type you are trying to delete does not exist.');
    }
    
}
