<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Shift extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Shift_model');
    } 

    /*
     * Listing of shifts
     */
    function index()
    {
        $data['shifts'] = $this->Shift_model->get_all_shifts();
        
        $data['_view'] = 'shift/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new shift
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
            );
            
            $shift_id = $this->Shift_model->add_shift($params);
            redirect('shift/index');
        }
        else
        {            
            $data['_view'] = 'shift/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a shift
     */
    function edit($id)
    {   
        // check if the shift exists before trying to edit it
        $data['shift'] = $this->Shift_model->get_shift($id);
        
        if(isset($data['shift']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
                );

                $this->Shift_model->update_shift($id,$params);            
                redirect('shift/index');
            }
            else
            {
                $data['_view'] = 'shift/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The shift you are trying to edit does not exist.');
    } 

    /*
     * Deleting shift
     */
    function remove($id)
    {
        $shift = $this->Shift_model->get_shift($id);

        // check if the shift exists before trying to delete it
        if(isset($shift['id']))
        {
            $this->Shift_model->delete_shift($id);
            redirect('shift/index');
        }
        else
            show_error('The shift you are trying to delete does not exist.');
    }
    
}
