<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Account_statu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get account_statu by id
     */
    function get_account_statu($id)
    {
        return $this->db->get_where('account_status',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all account_status
     */
    function get_all_account_status()
    {
        $this->db->order_by('id');
        return $this->db->get('account_status')->result_array();
    }
        
    /*
     * function to add new account_statu
     */
    function add_account_statu($params)
    {
        $this->db->insert('account_status',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update account_statu
     */
    function update_account_statu($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('account_status',$params);
    }
    
    /*
     * function to delete account_statu
     */
    function delete_account_statu($id)
    {
        return $this->db->delete('account_status',array('id'=>$id));
    }
}
