<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bus_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bus by id
     */
    function get_bus($id)
    {
        return $this->db->get_where('buses',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all buses count
     */
    function get_all_buses_count()
    {
        $this->db->from('buses');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all buses
     */
    function get_all_buses($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('buses')->result_array();
    }
        
    /*
     * function to add new bus
     */
    function add_bus($params)
    {
        $this->db->insert('buses',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bus
     */
    function update_bus($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('buses',$params);
    }
    
    /*
     * function to delete bus
     */
    function delete_bus($id)
    {
        return $this->db->delete('buses',array('id'=>$id));
    }
}
