<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Contractor_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get contractor by id
     */
    function get_contractor($id)
    {
        return $this->db->get_where('contractor',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all contractors
     */
    function get_all_contractors()
    {
        $this->db->order_by('id');
        return $this->db->get('contractor')->result_array();
    }
        
    /*
     * function to add new contractor
     */
    function add_contractor($params)
    {
        $this->db->insert('contractor',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update contractor
     */
    function update_contractor($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('contractor',$params);
    }
    
    /*
     * function to delete contractor
     */
    function delete_contractor($id)
    {
        return $this->db->delete('contractor',array('id'=>$id));
    }
}
