<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Driver_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get driver by id
     */
    function get_driver($id)
    {
        return $this->db->get_where('driver',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all driver
     */
    function get_all_driver()
    {
        $this->db->order_by('id');
        return $this->db->get('driver')->result_array();
    }
        
    /*
     * function to add new driver
     */
    function add_driver($params)
    {
        $this->db->insert('driver',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update driver
     */
    function update_driver($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('driver',$params);
    }
    
    /*
     * function to delete driver
     */
    function delete_driver($id)
    {
        return $this->db->delete('driver',array('id'=>$id));
    }
}
