<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Employee_type_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get employee_type by id
     */
    function get_employee_type($id)
    {
        return $this->db->get_where('employee_type',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all employee_type
     */
    function get_all_employee_type()
    {
        $this->db->order_by('id');
        return $this->db->get('employee_type')->result_array();
    }
        
    /*
     * function to add new employee_type
     */
    function add_employee_type($params)
    {
        $this->db->insert('employee_type',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update employee_type
     */
    function update_employee_type($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('employee_type',$params);
    }
    
    /*
     * function to delete employee_type
     */
    function delete_employee_type($id)
    {
        return $this->db->delete('employee_type',array('id'=>$id));
    }
}
