<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Employee_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get employee by id
     */
    function get_employee($id)
    {
        return $this->db->get_where('employees',array('id'=>$id))->row_array();
    }

    /*
     * Get employee by email
     */
    function get_employee_by_email_and_password($email,$password)
    {
        return $this->db->get_where('employees',array('email'=>$email, 'password'=>$password))->row_array();
    }
        
    /*
     * Get all employees
     */
    function get_all_employees()
    {
        $this->db->order_by('id');
        return $this->db->get('employees')->result_array();
    }
        
    /*
     * function to add new employee
     */
    function add_employee($params)
    {
        $this->db->insert('employees',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update employee
     */
    function update_employee($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('employees',$params);
    }
    
    /*
     * function to delete employee
     */
    function delete_employee($id)
    {
        return $this->db->delete('employees',array('id'=>$id));
    }
}
