<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Route_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get route by id
     */
    function get_route($id)
    {
        return $this->db->get_where('routes',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all routes
     */
    function get_all_routes()
    {
        $this->db->order_by('id');
        return $this->db->get('routes')->result_array();
    }
        
    /*
     * function to add new route
     */
    function add_route($params)
    {
        $this->db->insert('routes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update route
     */
    function update_route($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('routes',$params);
    }
    
    /*
     * function to delete route
     */
    function delete_route($id)
    {
        return $this->db->delete('routes',array('id'=>$id));
    }
}
