<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Shift_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get shift by id
     */
    function get_shift($id)
    {
        return $this->db->get_where('shifts',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all shifts
     */
    function get_all_shifts()
    {
        $this->db->order_by('id');
        return $this->db->get('shifts')->result_array();
    }
        
    /*
     * function to add new shift
     */
    function add_shift($params)
    {
        $this->db->insert('shifts',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update shift
     */
    function update_shift($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('shifts',$params);
    }
    
    /*
     * function to delete shift
     */
    function delete_shift($id)
    {
        return $this->db->delete('shifts',array('id'=>$id));
    }
}
