<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Track_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get track by id
     */
    function get_track($id)
    {
        return $this->db->get_where('track',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all track
     */
    function get_all_track()
    {
        $this->db->order_by('id');
        return $this->db->get('track')->result_array();
    }
        
    /*
     * function to add new track
     */
    function add_track($params)
    {
        $this->db->insert('track',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update track
     */
    function update_track($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('track',$params);
    }
    
    /*
     * function to delete track
     */
    function delete_track($id)
    {
        return $this->db->delete('track',array('id'=>$id));
    }
}
